### ISSUE TITLE
About CRD Loss

### ISSUE THREAD

**Issue by Alva-2020** [AberHu/Knowledge-Distillation-Zoo#4]
Thanks for sharing. About CRD LOSS, why the student/teacher anchor is random initialized contant? Hope you can reply. Thanks

**Comment by AberHu** [comment]
The memory bank is updated by moving average with a momentum of `nce_mom`, so both random initialization and zero initialization work. However, if zero initialization, in the first or the first few forward passes, the `weight_t` and `weight_s` are zeros, making the `out_t` and `out_s` are zeros. In this situation, CRD loss is destroyed.

**Comment by Alva-2020** [comment]
Thank you so much. I got it.
